# Execute only a specific tag in a playbook
# ansible-playbook tags.yml --list-tags
# ansible-playbook tags.yml --tags ntp

# Execute all except a a specific tag in a playbook
# ansible-playbook tags.yml --skip-tags ntp
---
- hosts: webservers
  become: yes

  tasks:
    - name: Install Apache2
      apt:
       name: apache2
       state: present
       # Update package list
       update_cache: yes
       # Only update package list if older than 3600 seconds (1hr)
       cache_valid_time: 3600
      tags: apache2

    - name: Install NTP
      apt:
       name: ntp
       state: present
      tags: ntp

    - name: Start NTP
      service: name=ntp state=started enabled=yes
      tags: ntp_start
