---
- hosts: webservers

  tasks:
    - name: Create a file
      file:
       # See host_list file for definition of {{temp_file}} 
       dest: '{{temp_file}}'
       # Use command line option to set file_state (touch=create)
       # ansible-playbook inventoryVars.yml -e file_state=touch
       state: '{{file_state}}'
      when: temp_file is defined
